CREATE ROLE GLUHX_ROLE NOT IDENTIFIED;

GRANT CONNECT TO GLUHX_ROLE;

GRANT CREATE ANY TABLE TO GLUHX_ROLE;
GRANT ALTER ANY TABLE TO GLUHX_ROLE;
GRANT DROP ANY TABLE TO GLUHX_ROLE;

GRANT SELECT ANY TABLE TO GLUHX_ROLE;

GRANT ALTER ANY TRIGGER TO GLUHX;
GRANT CREATE ANY TRIGGER TO GLUHX;
GRANT DROP ANY TRIGGER TO GLUHX;

GRANT ALTER ANY PROCEDURE TO GLUHX;
GRANT CREATE ANY PROCEDURE TO GLUHX;
GRANT DROP ANY PROCEDURE TO GLUHX;
GRANT EXECUTE ANY PROCEDURE TO GLUHX;

GRANT ALTER ANY SEQUENCE TO GLUHX;
GRANT CREATE ANY SEQUENCE TO GLUHX;
GRANT DROP ANY SEQUENCE TO GLUHX;


GRANT GLUHX_ROLE TO GLUHX;