DROP TABLE TPLG_PCB_Library CASCADE CONSTRAINTS;
DROP TABLE TPLG_Footprint CASCADE CONSTRAINTS;
DROP TABLE TPLG_Pad CASCADE CONSTRAINTS;
DROP SEQUENCE S_TPLG_PCB_Library;
DROP SEQUENCE S_TPLG_Footprint;
DROP SEQUENCE S_TPLG_Pad;