CREATE USER GLUHX IDENTIFIED BY gluhx;

GRANT CONNECT TO GLUHX;

GRANT CREATE ANY TABLE TO GLUHX;
GRANT ALTER ANY TABLE TO GLUHX;
GRANT DROP ANY TABLE TO GLUHX;

GRANT SELECT ANY TABLE TO GLUHX;

GRANT ALTER ANY TRIGGER TO GLUHX;
GRANT CREATE ANY TRIGGER TO GLUHX;
GRANT DROP ANY TRIGGER TO GLUHX;

GRANT ALTER ANY PROCEDURE TO GLUHX;
GRANT CREATE ANY PROCEDURE TO GLUHX;
GRANT DROP ANY PROCEDURE TO GLUHX;
GRANT EXECUTE ANY PROCEDURE TO GLUHX;

GRANT ALTER ANY SEQUENCE TO GLUHX;
GRANT CREATE ANY SEQUENCE TO GLUHX;
GRANT DROP ANY SEQUENCE TO GLUHX;
