GRANT ALTER ANY TRIGGER TO GLUHX;
GRANT ALTER ANY PROCEDURE TO GLUHX;
GRANT CREATE ANY TRIGGER TO GLUHX;
GRANT CREATE ANY PROCEDURE TO GLUHX;
GRANT DROP ANY TRIGGER TO GLUHX;
GRANT DROP ANY PROCEDURE TO GLUHX;
GRANT EXETUCE ANY PROCEDURE TO GLUHX;
